language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t igorvl/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true igorvl/react-test npm test

after_success:
  - docker build -t igorvl/multi-client ./client
  - docker build -t igorvl/multi-nginx ./nginx
  - docker build -t igorvl/muilt-server ./server
  - docker build -t igorvl/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin

  - docker push igorvl/multi-client
  - docker push igorvl/multi-nginx
  - docker push igorvl/multi-server
  - docker push igorvl/multi-worker